-- 0006 — Bot Exhibition games.
--
-- Stores results of bot-vs-bot games generated by the scheduled cron
-- handler (every 30 minutes). Separate from the user `games` table
-- because:
--   1. No user_id — neither side is a person, so the games table's
--      user_id NOT NULL constraint doesn't fit.
--   2. No rating impact — exhibition games are showcase content, not
--      ranked play. Adding them to `games` would skew bot ratings.
--   3. Cleaner query for the public "recent exhibitions" feed.
--
-- Schema mirrors `games` where it makes sense (moves_json, final_fen)
-- so a future merge / unified replay viewer can read both.

CREATE TABLE IF NOT EXISTS bot_exhibition_games (
  id TEXT PRIMARY KEY,
  white_bot_id TEXT NOT NULL,
  black_bot_id TEXT NOT NULL,
  -- 'white-wins' | 'black-wins' | 'draw' | 'truncated' (ply cap reached)
  outcome TEXT NOT NULL,
  ply_count INTEGER NOT NULL,
  moves_json TEXT NOT NULL,
  final_fen TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  FOREIGN KEY (white_bot_id) REFERENCES users(id),
  FOREIGN KEY (black_bot_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_exhibition_created_desc
  ON bot_exhibition_games(created_at DESC);
